sudo: false
dist: trusty
language: node_js
node_js:
  - "8"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - npm install npm@5 -g
  - npm install -g @angular/cli@latest
  - npm cache verify
  - npm prune
  - npm update



install:
  - npm install