sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

env:
  DOCKER_COMPOSE_VERSION :1.12.0

cache:
  directories:
    - node_modules

before_install:
  - npm install npm@5 -g
  - npm install -g @angular/cli@latest
  - npm install -g karma
  - npm install -g mocha
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install -U docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build && docker-compose up -d mongodb node

install:
  - npm install && cd server && npm install

script: npm run server:test