version: "2"
volumes:
  mongodb_data:
  nodemodules_data:

services:
  redis:
    image: redis
    hostname: redis
    restart: always

  mongodb:
    build:
      context: ./mongodb
    volumes:
      - mongodb_data:/data
  node:
    extends:
      file: docker-compose-base.yml
      service: mean-service
    build:
      context: ./server
    hostname: node
    volumes:
      - "./server:/app"
      - nodemodules_data:/app/node_modules/
    links:
     - nginx
     - mongodb
     - redis
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "./dist:/usr/share/nginx/html"